### ISSUE TITLE
namespace error in test/afh/chain/free_energy_finite.cpp

### ISSUE THREAD

**Issue by CaoRX** [todo-group/exact#1]
As I am learning to use git and GitHub, I have cloned this repository and tried to compile it. However, make cannot work for the function "generate" in test/afh/chain/free_energy_finite.cpp is not found. That is because the /afh/chain/heisenberg.hpp was modified after the final update of test/afh/chain/free_energy_finite.cpp. So "generate" should be changed to "exact::afh::generate" to make it work.

**Comment by wistaria** [comment]
@CaoRX 
Thank you for your report. Fixed in 50f01d2824692c88820bc3817fa0602007ace422.
